### ISSUE TITLE
Can this work for Godot 4+ multiplayer open-world chunk system?

### ISSUE THREAD

**Issue by WithinAmnesia** [KvaGram/AdventureQuests#1]
I am doing a from scratch build now for the multiplayer chunk system. What should I do for the server and the data and chunk storage?
I have a few leads and some more thoughts and resources can be found here:
https://github.com/WithinAmnesia/ARPG/discussions/16 <Start fresh thread.
https://github.com/WithinAmnesia/ARPG/discussions/15 <Previous start thread.
It was suggested I build a from scratch Multiplayer seamless chunk system that eventually be put together where it can handle 2K-16K+ players on the same server. What should be done for a web deployment to also run on a browser? I was suggested to try and do a chunk storage system similar to Minecraft or Terraria where each chunk is stored individually and accessed by the server in communication with the player clients. What should be done to solve this chunk puzzle? All feedback is welcome.

**Comment by KvaGram** [comment]
I am quite confident you are on the wrong git here.
This is some old abandonware I worked on for my minecraft server, loooong ago.
As for your project, I am not sure what you are trying to do, nor do I know how to help you.
Closing this issue.

**Comment by WithinAmnesia** [comment]
Thats okay. I'm looking for how to save multiplayer chunk data now any suggestions / examples?

**Comment by KvaGram** [comment]
> Thats okay. I'm looking for how to save multiplayer chunk data now any suggestions / examples?

I just had a look at your profile. You spammed this same question in well over a hundred other reposetories.
You rightfully should be banned from github.

**Comment by WithinAmnesia** [comment]
> > Thats okay. I'm looking for how to save multiplayer chunk data now any suggestions / examples?
> 
> I just had a look at your profile. You spammed this same question in well over a hundred other reposetories. You rightfully should be banned from github.

I am looking for help this is a difficult puzzle to solve. Check my forums and thread posts, there are very few people who know how to solve these big game puzzles. I have to be proactive and search for experience people. Most people don't use the forums often for they just do their own lives. You cant just expect people to show up and help you when they are busy with their own lives. Socialize and like go door to door and run a business you will grow and learn more and have a better attitude as well. Godot is not easy to find help with with new issues especially complex ones. Also be nicer you will have a better life treating people better and people will treat you better too. Take care mate.
